In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"

In [3]:
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [5]:
txt ="""The global recovery is slowing amid widening divergences among economic sectors and regions

Global growth is projected to fall from an estimated 3.5 percent in 2022 to 3.0 percent in both 2023 and 2024. While the forecast for 2023 is modestly higher than predicted in the April 2023 World Economic Outlook (WEO), it remains weak by historical standards. The rise in central bank policy rates to fight inflation continues to weigh on economic activity. Global headline inflation is expected to fall from 8.7 percent in 2022 to 6.8 percent in 2023 and 5.2 percent in 2024. Underlying (core) inflation is projected to decline more gradually, and forecasts for inflation in 2024 have been revised upward.

The recent resolution of the US debt ceiling standoff and, earlier this year, strong action by authorities to contain turbulence in US and Swiss banking reduced the immediate risks of financial sector turmoil. This moderated adverse risks to the outlook. However, the balance of risks to global growth remains tilted to the downside. Inflation could remain high and even rise if further shocks occur, including those from an intensification of the war in Ukraine and extreme weather-related events, triggering more restrictive monetary policy. Financial sector turbulence could resume as markets adjust to further policy tightening by central banks. China’s recovery could slow, in part as a result of unresolved real estate problems, with negative cross-border spillovers. Sovereign debt distress could spread to a wider group of economies. On the upside, inflation could fall faster than expected, reducing the need for tight monetary policy, and domestic demand could again prove more resilient.

In most economies, the priority remains achieving sustained disinflation while ensuring financial stability. Therefore, central banks should remain focused on restoring price stability and strengthen financial supervision and risk monitoring. Should market strains materialize, countries should provide liquidity promptly while mitigating the possibility of moral hazard. They should also build fiscal buffers, with the composition of fiscal adjustment ensuring targeted support for the most vulnerable. Improvements to the supply side of the economy would facilitate fiscal consolidation and a smoother decline"""

In [6]:
tokens = tokenizer(txt, return_tensors="pt", 
                max_length=512,
                truncation=True,
                padding="max_length",
                add_special_tokens=True)


In [7]:
tokens

{'input_ids': tensor([[  101,  1996,  3795,  7233,  2003, 18068, 13463, 17973, 17856, 17905,
          2015,  2426,  3171, 11105,  1998,  4655,  3795,  3930,  2003, 11310,
          2000,  2991,  2013,  2019,  4358,  1017,  1012,  1019,  3867,  1999,
         16798,  2475,  2000,  1017,  1012,  1014,  3867,  1999,  2119, 16798,
          2509,  1998, 16798,  2549,  1012,  2096,  1996, 19939,  2005, 16798,
          2509,  2003, 10754,  2135,  3020,  2084, 10173,  1999,  1996,  2258,
         16798,  2509,  2088,  3171, 17680,  1006,  2057,  2080,  1007,  1010,
          2009,  3464,  5410,  2011,  3439,  4781,  1012,  1996,  4125,  1999,
          2430,  2924,  3343,  6165,  2000,  2954, 14200,  4247,  2000, 17042,
          2006,  3171,  4023,  1012,  3795, 17653, 14200,  2003,  3517,  2000,
          2991,  2013,  1022,  1012,  1021,  3867,  1999, 16798,  2475,  2000,
          1020,  1012,  1022,  3867,  1999, 16798,  2509,  1998,  1019,  1012,
          1016,  3867,  1999, 16798,  

[CLS] = 101
[SEP] = 102
[MASK]= 103
[UNK] = 100
[PAD] = 0


In [9]:
outputs = model(**tokens)

In [10]:
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 3.0746, -2.5698]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [11]:
outputs[0]

tensor([[ 3.0746, -2.5698]], grad_fn=<AddmmBackward0>)

In [12]:
import torch.nn.functional as F

In [14]:
probs = F.softmax(outputs[0], dim=-1)

In [15]:
probs

tensor([[0.9965, 0.0035]], grad_fn=<SoftmaxBackward0>)

In [17]:
import torch
preds = torch.argmax(probs)

In [19]:
preds.item()

0

In [20]:
txt2 = """ i feel good"""

In [21]:
tokens2 = tokenizer(txt2, return_tensors="pt",
                    max_length=512,
                    truncation=True,
                    padding="max_length",
                    add_special_tokens=True)
                    

In [22]:
output2 = model(**tokens2)

In [23]:
output2[0]

tensor([[-4.2158,  4.5907]], grad_fn=<AddmmBackward0>)

In [25]:
probs2 = F.softmax(output2[0], dim=-1)

In [26]:
probs2

tensor([[1.4973e-04, 9.9985e-01]], grad_fn=<SoftmaxBackward0>)

In [27]:
preds2 = torch.argmax(probs2)


In [28]:
preds2.item()

1